version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    groups:
      # Core framework updates
      framework:
        patterns:
          - "next*"
          - "react*"
          - "@next/*"
          - "@types/react*"
          - "tailwind*"
          - "@tailwindcss/*"
      
      # Content and markdown processing
      content:
        patterns:
          - "contentlayer*"
          - "rehype*"
          - "remark*"
          - "*-matter"
          - "reading-time"
          - "github-slugger"
      
      # Development tools
      dev-tools:
        dependency-type: "development"
    
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"